#!/usr/bin/env bash
# shellcheck disable=SC2015  # file-level: `[ -n ] && [ -d ] || die` is a guard, not if-then-else (must precede the first command)
# Regression tests for scripts/check-routine-prompt.sh.
#
# The guard is a flat list of literal-token assertions over a checked-in
# Routine prompt, so the only way it can regress is by having a `require` call
# trimmed -- which leaves a script that still runs, still exits 0, and still
# looks healthy. A grep of the guard for its own token list would cement
# whatever spelling shipped (the #1417 -> #1819 lesson), so every case here
# EXECUTES the guard against a fixture tree and asserts on its report.
#
# Both directions are covered: a faithful copy of the prompt must report
# STATUS=OK, and each stripped token must be flagged by name. Without the
# first half every "is flagged" assertion would also hold for a guard that
# rejects everything; without the second, for a guard that scans nothing.
#
# Run: bash scripts/tests/test-check-routine-prompt.sh
# Exit 0 = all tests pass, Exit 1 = failures
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
GUARD="$SCRIPT_DIR/check-routine-prompt.sh"
REAL_PROMPT="$REPO_ROOT/docs/routines/resolve-claude-plugins-issues.md"
REAL_README="$REPO_ROOT/docs/routines/README.md"
PASS=0
FAIL=0

WORK=$(mktemp -d) || { echo "mktemp -d failed" >&2; exit 1; }
[ -n "$WORK" ] && [ -d "$WORK" ] || { echo "bad sandbox dir" >&2; exit 1; }
trap 'rm -rf "$WORK"' EXIT

[ -f "$REAL_PROMPT" ] || { echo "missing $REAL_PROMPT" >&2; exit 1; }
[ -f "$REAL_README" ] || { echo "missing $REAL_README" >&2; exit 1; }

# Seed a fixture root holding a verbatim copy of the checked-in routine docs.
seed() {
  local root="$1"
  mkdir -p "$root/docs/routines"
  cp "$REAL_PROMPT" "$root/docs/routines/resolve-claude-plugins-issues.md"
  cp "$REAL_README" "$root/docs/routines/README.md"
}

run_key() {
  # run_key DIR KEY -> value of KEY= from the guard's report
  bash "$GUARD" "$1" 2>&1 | grep -E "^$2=" | cut -d= -f2-
}

assert_eq() {
  local desc="$1" expected="$2" got="$3"
  if [ "$got" = "$expected" ]; then
    printf "  PASS: %s\n" "$desc"; PASS=$((PASS + 1))
  else
    printf "  FAIL: %s (expected '%s', got '%s')\n" "$desc" "$expected" "$got"; FAIL=$((FAIL + 1))
  fi
}

assert_contains() {
  local desc="$1" needle="$2" haystack="$3"
  case "$haystack" in
    *"$needle"*) printf "  PASS: %s\n" "$desc"; PASS=$((PASS + 1)) ;;
    *) printf "  FAIL: %s (missing '%s')\n" "$desc" "$needle"; FAIL=$((FAIL + 1)) ;;
  esac
}

# strip_token DIR TOKEN -- delete every prompt line carrying TOKEN, and assert
# the fixture genuinely changed. Without the fixture-validity check a token
# that has drifted out of the prompt would silently make its case a no-op.
strip_token() {
  local root="$1" token="$2"
  local f="$root/docs/routines/resolve-claude-plugins-issues.md"
  local before after
  before=$(wc -l < "$f")
  grep -vF "$token" "$f" > "$f.tmp" && mv "$f.tmp" "$f"
  after=$(wc -l < "$f")
  if [ "$before" -eq "$after" ]; then
    printf "  FAIL: fixture validity -- token '%s' was not present to strip\n" "$token"
    FAIL=$((FAIL + 1))
  fi
}

echo "=== check-routine-prompt regression tests ==="

# 0. Guard integrity: the structured block is emitted at all. A silent guard
#    would make every ISSUE_COUNT assertion below compare against "".
clean="$WORK/clean"; seed "$clean"
report="$(bash "$GUARD" "$clean" 2>&1)"
assert_contains "guard emits its structured report block" "=== END ROUTINE PROMPT ===" "$report"

# 1. Positive control -- the checked-in prompt, copied verbatim, is compliant.
assert_eq "faithful prompt reports STATUS=OK" "OK" "$(run_key "$clean" STATUS)"
assert_eq "faithful prompt reports ISSUE_COUNT=0" "0" "$(run_key "$clean" ISSUE_COUNT)"
assert_eq "faithful prompt reports PROMPT_PRESENT=true" "true" "$(run_key "$clean" PROMPT_PRESENT)"

# 2. Non-vacuity -- the guard actually opened a routine. Without this, every
#    "clean" assertion above holds for a walk that discovered nothing.
assert_eq "faithful fixture discovers one routine" "1" "$(run_key "$clean" ROUTINES_DISCOVERED)"
assert_eq "faithful fixture guards one routine" "1" "$(run_key "$clean" ROUTINES_GUARDED)"

# 3. The live repo is compliant too, over a non-empty corpus.
assert_eq "live repo reports STATUS=OK" "OK" "$(bash "$GUARD" 2>&1 | grep -E '^STATUS=' | cut -d= -f2)"
assert_eq "live repo discovers one routine" "1" "$(bash "$GUARD" 2>&1 | grep -E '^ROUTINES_DISCOVERED=' | cut -d= -f2)"

# 4. Each load-bearing token, stripped one at a time, must be flagged by name.
#    One case per invariant group in the guard's header.
for token in \
  "_Generated by [Claude Code](https://claude.ai/code)_" \
  "routine:needs-decision v2" \
  "Verify the signals, not the length" \
  "no comment carries your footer or marker" \
  "Do not fall through to (b)" \
  "issues/comments/<id> -X PATCH" \
  "Answer recorded, work deferred:" \
  "must account for every labelled issue" \
  ; do
  slug="$WORK/strip-$(printf '%s' "$token" | tr -c 'a-zA-Z0-9' '-')"
  seed "$slug"
  strip_token "$slug" "$token"
  out="$(bash "$GUARD" "$slug" 2>&1)"
  assert_eq "stripping '$token' sets STATUS=ERROR" "ERROR" "$(printf '%s\n' "$out" | grep -E '^STATUS=' | cut -d= -f2)"
  assert_contains "stripping '$token' names it in the report" "$token" "$out"
done

# 5. Coverage -- a NEW routine prompt fires the pre-commit trigger but is
#    asserted on by nothing. That must be an error naming the file, not a
#    silent pass (the allowlist-drift shape #2164 named).
uncovered="$WORK/uncovered"; seed "$uncovered"
printf 'A second routine prompt nothing asserts on.\n' > "$uncovered/docs/routines/second-routine.md"
out="$(bash "$GUARD" "$uncovered" 2>&1)"
assert_eq "an unguarded routine prompt sets STATUS=ERROR" "ERROR" "$(printf '%s\n' "$out" | grep -E '^STATUS=' | cut -d= -f2)"
assert_eq "an unguarded routine prompt is counted as discovered" "2" "$(printf '%s\n' "$out" | grep -E '^ROUTINES_DISCOVERED=' | cut -d= -f2)"
assert_contains "the unguarded routine is named" "docs/routines/second-routine.md" "$out"
if bash "$GUARD" --strict "$uncovered" >/dev/null 2>&1; then
  printf "  FAIL: --strict should exit 1 on an unguarded routine prompt\n"; FAIL=$((FAIL + 1))
else
  printf "  PASS: --strict exits 1 on an unguarded routine prompt\n"; PASS=$((PASS + 1))
fi

# 6. Narrowness -- the coverage check must not flag the directory's own README,
#    which is documentation rather than a prompt. Without this the guard would
#    be red on the tree it shipped with.
assert_eq "README.md is not counted as a routine prompt" "1" "$(run_key "$clean" ROUTINES_DISCOVERED)"

# 7. A missing prompt is reported, not silently skipped.
empty="$WORK/empty"; mkdir -p "$empty/docs/routines"
assert_eq "absent prompt reports PROMPT_PRESENT=false" "false" "$(run_key "$empty" PROMPT_PRESENT)"
assert_eq "absent prompt sets STATUS=ERROR" "ERROR" "$(run_key "$empty" STATUS)"

# 8. --strict exit codes on the compliant tree.
if bash "$GUARD" --strict "$clean" >/dev/null 2>&1; then
  printf "  PASS: --strict exits 0 on a compliant prompt\n"; PASS=$((PASS + 1))
else
  printf "  FAIL: --strict should exit 0 on a compliant prompt\n"; FAIL=$((FAIL + 1))
fi

echo ""
echo "PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ]
