#!/usr/bin/env bash
# check-routine-prompt.sh — semantic guard for checked-in Routine prompts.
#
# THE CONVENTION (docs/routines/README.md)
# A scheduled Routine that queues decisions in an issue thread posts as the repo
# owner, so authorship cannot distinguish its own comments from the owner's
# replies. Textual signals are the only discriminator, and the prompt must:
#   1. require an identity FOOTER on every comment it posts (not just questions),
#   2. require the needs-decision MARKER on question comments,
#   3. VERIFY both after posting — a length check passes a missing marker,
#   4. carry an explicit NO-ANCHOR recovery branch rather than falling through to
#      the silent "do nothing" branch,
#   5. reserve "Proceeding on:" for an actually-unblocked issue,
#   6. account for every labelled issue in the run summary.
#
# WHY A SEMANTIC GUARD
# Between 2026-08-11 and 2026-09-03 the live Routine stopped emitting its own
# mandatory marker line. Nothing surfaced it: the undecidable case falls through
# to "do nothing at all. Silence here is the feature", so a dropped reply is
# indistinguishable from correct operation (#2141 sat answered and unread for a
# month). A future edit that trims the prompt "for length" would reintroduce it
# just as invisibly. This asserts the load-bearing tokens survive
# (regression-testing.md: semantic > syntactic).
#
# NOTE: this guards the CHECKED-IN prompt only. The Routine itself is stored
# server-side and must be updated by hand; see docs/routines/README.md.
#
# Output: structured KEY=VALUE per .claude/rules/structured-script-output.md.
#   --strict  exit 1 when ISSUE_COUNT > 0 (for pre-commit / CI). Default: report.

set -uo pipefail

STRICT=0
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
for arg in "$@"; do
    case "$arg" in
        --strict) STRICT=1 ;;
        *) [ -d "$arg" ] && ROOT_DIR="$arg" ;;
    esac
done

README="$ROOT_DIR/docs/routines/README.md"
PROMPT="$ROOT_DIR/docs/routines/resolve-claude-plugins-issues.md"

issue_count=0
declare -a issues=()

# require FILE TOKEN MESSAGE — assert a literal token is present (file must exist).
require() {
    local file="$1" token="$2" msg="$3" rel
    rel="${file#"$ROOT_DIR"/}"
    if [ ! -f "$file" ]; then
        issue_count=$((issue_count + 1))
        issues+=("  - SEVERITY=ERROR FILE=$rel MSG=missing file ($msg)")
        return
    fi
    if ! grep -qF "$token" "$file"; then
        issue_count=$((issue_count + 1))
        issues+=("  - SEVERITY=ERROR FILE=$rel TOKEN=\"$token\" MSG=$msg")
    fi
}

# (1) Identity footer — the author-independent signal. Without it the Routine's
#     own non-question comments are unattributable and corrupt the anchor scan.
require "$PROMPT" "_Generated by [Claude Code](https://claude.ai/code)_" \
    "prompt lost the identity footer requirement (routine comments become indistinguishable from the owner's)"
require "$PROMPT" "share one GitHub identity" \
    "prompt lost the shared-identity premise that motivates the textual signals"

# (2) The marker itself, and the escaped form a naive matcher would miss.
require "$PROMPT" "<!-- routine:needs-decision v1 -->" \
    "prompt lost the needs-decision marker line"
require "$PROMPT" "&lt;!-- routine:needs-decision v1 --&gt;" \
    "prompt lost the entity-escaped marker form (an escaped marker is still the routine's)"

# (3) Verification must assert the signals, not the comment length.
require "$PROMPT" "Verify the signals, not the length" \
    "prompt reverted to a length-only post-check, which a missing marker passes trivially"

# (4) The no-anchor branch. This is the one that stops a dropped reply from
#     being absorbed by the silent branch.
require "$PROMPT" "no comment carries your footer or marker" \
    "prompt lost the no-anchor recovery branch (dropped replies fall through to silence again)"
require "$PROMPT" "Do not fall through to (b)" \
    "prompt lost the explicit instruction not to default to the silent branch"

# (5) "Proceeding on:" must stay reserved for an actual unblock, or a deferral
#     comment reads to a later run as a consumed reply (#2119).
require "$PROMPT" "Answer recorded, work deferred:" \
    "prompt lost the distinct deferral wording (deferrals get misread as consumed replies)"
require "$PROMPT" "Reserve the literal phrase" \
    "prompt lost the reservation of 'Proceeding on:' for actual unblocking"

# (6) Non-silent default: every labelled issue is accounted for.
require "$PROMPT" "must account for every labelled issue" \
    "prompt lost the run-summary accounting requirement (silence becomes undetectable again)"

# Starvation guard — an answered issue must outrank fresh autonomous work.
require "$PROMPT" "sort ahead of" \
    "prompt lost the reply-unblocked priority rule (answered issues starve behind newer work)"

# The doc that explains why all of the above exists.
require "$README" "resolve-claude-plugins-issues.md" \
    "routines README lost its index entry for the prompt"
require "$README" "update_trigger" \
    "routines README lost the note that the Routine must be updated by hand"

status="OK"
[ "$issue_count" -gt 0 ] && status="ERROR"

echo "=== ROUTINE PROMPT ==="
echo "PROMPT_PRESENT=$([ -f "$PROMPT" ] && echo true || echo false)"
echo "STATUS=$status"
echo "ISSUE_COUNT=$issue_count"
if [ "$issue_count" -gt 0 ]; then
    echo "ISSUES:"
    printf '%s\n' "${issues[@]}"
    echo ""
    echo "FIX: restore the missing token; see docs/routines/README.md"
fi
echo "=== END ROUTINE PROMPT ==="

if [ "$STRICT" -eq 1 ] && [ "$issue_count" -gt 0 ]; then
    exit 1
fi
exit 0
