#!/usr/bin/env python3
"""Generate docs/CATALOG.md — the plugin catalog — from the marketplace.

Sources (nothing is hand-copied, so the catalog cannot drift):
  .claude-plugin/marketplace.json   name, category, description per plugin
  <plugin>/skills/**/SKILL.md       skill count (case-insensitive, as
                                    scripts/check-docs-index.sh counts them)
  <plugin>/agents/*.md              agent count

Usage:
  generate-catalog.py            write docs/CATALOG.md
  generate-catalog.py --check    exit 1 if docs/CATALOG.md differs from the
                                 generated content (CI); writes nothing
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MARKETPLACE = REPO_ROOT / ".claude-plugin" / "marketplace.json"
CATALOG = REPO_ROOT / "docs" / "CATALOG.md"
MARKETPLACE_NAME = "laurigates-claude-plugins"

# marketplace.json `category` slug -> heading, in display order. A slug missing
# here is an error, not a silent "Other" bucket: a new category needs a heading.
CATEGORIES = {
    "ai": "AI & Agents",
    "development": "Development",
    "language": "Languages",
    "quality": "Quality",
    "testing": "Testing",
    "ci-cd": "CI/CD",
    "infrastructure": "Infrastructure",
    "documentation": "Documentation",
    "communication": "Communication",
    "ux": "UX & Components",
    "automation": "Automation",
    "utilities": "Utilities",
    "gamedev": "Game Development",
}


def count_skills(plugin_dir: Path) -> int:
    skills = plugin_dir / "skills"
    if not skills.is_dir():
        return 0
    return sum(
        1 for p in skills.rglob("*") if p.is_file() and p.name.lower() == "skill.md"
    )


def count_agents(plugin_dir: Path) -> int:
    agents = plugin_dir / "agents"
    if not agents.is_dir():
        return 0
    return sum(1 for p in agents.glob("*.md") if p.is_file())


def plugin_rows(repo_root: Path) -> list[dict]:
    plugins = json.loads(MARKETPLACE.read_text())["plugins"]
    rows = []
    for p in plugins:
        category = p.get("category")
        if category not in CATEGORIES:
            sys.exit(
                f"error: {p['name']} has category {category!r}, which has no heading in "
                f"CATEGORIES ({Path(__file__).name}); add one"
            )
        plugin_dir = repo_root / p["source"]
        if not plugin_dir.is_dir():
            sys.exit(f"error: {p['name']} source {p['source']} is not a directory")
        rows.append(
            {
                "name": p["name"],
                "dir": plugin_dir.relative_to(repo_root).as_posix(),
                "category": category,
                "description": p["description"].replace("|", "\\|"),
                "skills": count_skills(plugin_dir),
                "agents": count_agents(plugin_dir),
            }
        )
    return rows


def render(rows: list[dict]) -> str:
    total_skills = sum(r["skills"] for r in rows)
    total_agents = sum(r["agents"] for r in rows)
    out = [
        "<!-- Generated by scripts/generate-catalog.py from .claude-plugin/marketplace.json",
        "     and the plugin directories. Do not edit by hand: run `just catalog`. -->",
        "",
        "# Plugin Catalog",
        "",
        (
            f"{len(rows)} plugins, {total_skills} skills, {total_agents} agents. "
            f"Install one in Claude Code with `claude plugin install <plugin>@{MARKETPLACE_NAME}`; "
            "the [README](../README.md#supported-harnesses) covers the other harnesses."
        ),
        "",
    ]
    for slug, heading in CATEGORIES.items():
        members = sorted(
            (r for r in rows if r["category"] == slug), key=lambda r: r["name"]
        )
        if not members:
            continue
        out += [
            f"## {heading}",
            "",
            "| Plugin | Skills | Agents | Description |",
            "|--------|-------:|-------:|-------------|",
        ]
        out += [
            f"| [{r['name']}](../{r['dir']}/) | {r['skills']} | {r['agents']} | {r['description']} |"
            for r in members
        ]
        out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    check = argv == ["--check"]
    if argv and not check:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    content = render(plugin_rows(REPO_ROOT))
    current = CATALOG.read_text() if CATALOG.is_file() else ""
    if check:
        if current == content:
            print("STATUS=OK")
            return 0
        print("STATUS=ERROR")
        print(
            f"MSG={CATALOG.relative_to(REPO_ROOT)} is stale; run `just catalog` and commit the result"
        )
        return 1
    if current != content:
        CATALOG.write_text(content)
        print(f"UPDATED={CATALOG.relative_to(REPO_ROOT)}")
    else:
        print(f"UNCHANGED={CATALOG.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
