#!/usr/bin/env python3
"""Generate Antigravity CLI lifecycle hooks from Claude Code plugin manifests.

Antigravity CLI (agy) supports lifecycle hooks via `hooks.json` in
`~/.gemini/config/hooks.json` (global) or `<workspace>/.agents/hooks.json` (project).

This generator projects the safety subset of Claude Code hooks into an Antigravity
hook suite:
  <plugin>/hooks.json                    \
  <plugin>/.claude-plugin/plugin.json#hooks > <out>/hooks.json + <out>/run-agy-hook.py
  <plugin>/hooks/<script>.sh              -> <out>/hook-scripts/<plugin>/hooks/

Contract:
  - PreToolUse on `run_command`:
      1. Claude Code variable emulation:
         Inspects `CommandLine` for `${CLAUDE_SKILL_DIR}`, `${CLAUDE_PLUGIN_ROOT}`,
         and `${CLAUDE_SESSION_ID}`. If present, resolves them against this
         checkout's skills and emits an `overwrite: { CommandLine: "export ...\n<cmd>" }`.
      2. Safety gate evaluation:
         Evaluates matching safety hooks (branch protection, secret protection,
         repo deletion guards, etc.). Exit 2 or JSON deny -> `decision: "deny"`.
         JSON ask -> `decision: "ask"`.
  - A script failure, missing script, or timeout FAILS OPEN (logs warning, allows).

Usage: generate-antigravity-hooks.py <repo_root> <out_dir> [--allow <plugin>/<script>]...
"""

import json
import re
import shutil
import sys
from pathlib import Path

# Command regex matching: bash "${CLAUDE_PLUGIN_ROOT}/hooks/<script>.sh"
COMMAND_RE = re.compile(
    r'^bash (?P<q>")?\$\{CLAUDE_PLUGIN_ROOT\}/hooks/(?P<script>[A-Za-z0-9._-]+\.sh)(?(q)"|)$'
)

# Cross-plugin lib references
CROSS_PLUGIN_LIB_RE = re.compile(r"([A-Za-z0-9_-]+-plugin)/hooks/lib/")

# Proven safety allowlist (parity with pi and opencode exports)
AGY_SAFETY_ALLOWLIST = {
    "hooks-plugin/branch-protection.sh": "blocks commits and pushes on the default branch",
    "hooks-plugin/secret-protection.sh": "blocks reads/writes of credential files and env dumps",
    "hooks-plugin/repo-deletion-safety.sh": "blocks rm -rf of a repo with unpushed work",
    "hooks-plugin/external-pr-merge-guard.sh": "blocks merging a PR authored outside the owner/bots",
    "hooks-plugin/branch-base-guard.sh": "confirms before branching off a stale base",
    "git-plugin/validate-pr-issue-links.sh": "validates issue-closing keywords before a PR is created",
    "git-plugin/check-pr-metadata-on-push.sh": "blocks a push that leaves the open PR's metadata stale",
    "git-plugin/check-branch-sync-on-push.sh": "confirms before committing onto a merged or behind branch",
    "terraform-plugin/validate-terraform-apply.sh": "blocks terraform apply -auto-approve / without a saved plan",
    "kubernetes-plugin/validate-kubectl-context.sh": "blocks mutating kubectl without an explicit --context",
    "kubernetes-plugin/inject-kubectl-dry-run.sh": "rewrites mutating kubectl to --dry-run=client first",
    "feedback-plugin/check-open-pr.sh": "blocks an unconditional force-push to a branch with an open PR",
}

GENERATED_MARKER = "Generated by scripts/generate-antigravity-hooks.py"


def normalize_timeout(value: object) -> int:
    """Normalize timeout to seconds (max 600)."""
    if not isinstance(value, (int, float)) or value <= 0:
        return 30
    if value > 600:
        return max(1, round(value / 1000.0))
    return int(value)


def discover_manifests(repo_root: Path):
    """Yield (plugin_name, plugin_dir, source_label, manifest_dict)."""
    for plugin_dir in sorted(p for p in repo_root.glob("*-plugin") if p.is_dir()):
        plugin_name = plugin_dir.name
        hooks_json = plugin_dir / "hooks.json"
        if hooks_json.is_file():
            try:
                yield (
                    plugin_name,
                    plugin_dir,
                    "hooks.json",
                    json.loads(hooks_json.read_text(encoding="utf-8")),
                )
            except (json.JSONDecodeError, OSError):
                continue
        plugin_json = plugin_dir / ".claude-plugin" / "plugin.json"
        if plugin_json.is_file():
            try:
                data = json.loads(plugin_json.read_text(encoding="utf-8"))
                declared = data.get("hooks")
                if isinstance(declared, dict):
                    yield plugin_name, plugin_dir, "plugin.json", {"hooks": declared}
            except (json.JSONDecodeError, OSError):
                continue


def copy_scripts(
    repo_root: Path, scripts: dict[str, set[str]], out_dir: Path
) -> tuple[int, list[str]]:
    """Copy referenced scripts and lib directories."""
    copied = 0
    libs = set()
    for plugin, names in scripts.items():
        for name in sorted(names):
            src = repo_root / plugin / "hooks" / name
            dst = out_dir / "hook-scripts" / plugin / "hooks" / name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied += 1
            try:
                text = src.read_text(errors="replace")
                if "/lib/" in text and (repo_root / plugin / "hooks" / "lib").is_dir():
                    libs.add(plugin)
                for p in CROSS_PLUGIN_LIB_RE.findall(text):
                    if (repo_root / p / "hooks" / "lib").is_dir():
                        libs.add(p)
            except OSError:
                continue

    for plugin in sorted(libs):
        dst = out_dir / "hook-scripts" / plugin / "hooks" / "lib"
        shutil.copytree(repo_root / plugin / "hooks" / "lib", dst, dirs_exist_ok=True)

    return copied, sorted(libs)


RUN_AGY_HOOK_PY_CONTENT = r'''#!/usr/bin/env python3
"""Antigravity CLI hook runner for Claude Code safety hooks and variable rewriting.
__MARKER__
"""

import hashlib
import json
import os
import re
import subprocess
import sys
from pathlib import Path

SKILL_DIR_REF = re.compile(r"\$\{CLAUDE_SKILL_DIR\}|\$CLAUDE_SKILL_DIR(?![A-Za-z0-9_])")
PLUGIN_ROOT_REF = re.compile(r"\$\{CLAUDE_PLUGIN_ROOT\}|\$CLAUDE_PLUGIN_ROOT(?![A-Za-z0-9_])")
SESSION_ID_REF = re.compile(r"\$\{CLAUDE_SESSION_ID(?:[}:])|\$CLAUDE_SESSION_ID(?![A-Za-z0-9_])")

SKILL_DIR_PATH_REF = re.compile(
    r"(?:\$\{CLAUDE_SKILL_DIR\}|\$CLAUDE_SKILL_DIR(?![A-Za-z0-9_]))/([^\s\"'`;|&<>()]+)"
)
PLUGIN_ROOT_PATH_REF = re.compile(
    r"(?:\$\{CLAUDE_PLUGIN_ROOT\}|\$CLAUDE_PLUGIN_ROOT(?![A-Za-z0-9_]))/([^\s\"'`;|&<>()]+)"
)


def load_manifest():
    here = Path(__file__).resolve().parent
    manifest_file = here / "hooks_manifest.json"
    if manifest_file.is_file():
        try:
            return json.loads(manifest_file.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"hooks": [], "repo_root": str(here)}


def extract_rel_paths(command: str, pattern: re.Pattern) -> list[str]:
    rels = set()
    for match in pattern.finditer(command):
        rel = match.group(1).rstrip("/")
        if rel and not re.search(r"[\$*?\[\]{}]", rel):
            rels.add(rel)
    return sorted(rels)


def resolve_claude_vars(command: str, repo_root: Path, conversation_id: str) -> dict[str, str]:
    needed = {}
    has_skill_dir = bool(SKILL_DIR_REF.search(command))
    has_plugin_root = bool(PLUGIN_ROOT_REF.search(command))
    has_session_id = bool(SESSION_ID_REF.search(command))

    if not (has_skill_dir or has_plugin_root or has_session_id):
        return {}

    skill_rels = extract_rel_paths(command, SKILL_DIR_PATH_REF)
    plugin_rels = extract_rel_paths(command, PLUGIN_ROOT_PATH_REF)

    # Search for candidate skill directory in repo
    matched_skill_dir = None
    matched_plugin_root = None

    if has_skill_dir or has_plugin_root:
        for p_dir in sorted(repo_root.glob("*-plugin")):
            skills_base = p_dir / "skills"
            if not skills_base.is_dir():
                continue
            for s_dir in sorted(skills_base.iterdir()):
                if not s_dir.is_dir():
                    continue
                # Check skill rels
                if all((s_dir / rel).exists() for rel in skill_rels) and all(
                    (p_dir / rel).exists() for rel in plugin_rels
                ):
                    matched_skill_dir = str(s_dir)
                    matched_plugin_root = str(p_dir)
                    break
            if matched_skill_dir:
                break

    if has_skill_dir and matched_skill_dir:
        needed["CLAUDE_SKILL_DIR"] = matched_skill_dir
    if has_plugin_root and matched_plugin_root:
        needed["CLAUDE_PLUGIN_ROOT"] = matched_plugin_root
    if has_session_id:
        sess_id = hashlib.sha256(conversation_id.encode("utf-8")).hexdigest()[:16]
        needed["CLAUDE_SESSION_ID"] = sess_id

    return needed


def parse_hook_decision(stdout_str: str) -> dict:
    """Parse JSON decision from a hook script if emitted."""
    trimmed = stdout_str.strip()
    if trimmed.startswith("{") and trimmed.endswith("}"):
        try:
            data = json.loads(trimmed)
            if isinstance(data, dict):
                perm = data.get("permissionDecision") or data.get("decision")
                reason = data.get("reason", "")
                if perm in ("deny", "block"):
                    return {"decision": "deny", "reason": reason}
                if perm == "ask":
                    return {"decision": "ask", "reason": reason}
        except Exception:
            pass
    return {}


def run_single_hook(entry: dict, script_path: Path, plugin_root: Path, command: str, conv_id: str, cwd: str) -> dict:
    """Execute a single shell safety hook."""
    if not script_path.is_file():
        return {"decision": "allow"}

    payload = {
        "tool_name": "Bash",
        "tool_input": {"command": command},
        "session_id": conv_id,
        "cwd": cwd,
    }

    env = os.environ.copy()
    env["CLAUDE_PLUGIN_ROOT"] = str(plugin_root)

    try:
        proc = subprocess.run(
            ["bash", str(script_path)],
            input=json.dumps(payload),
            text=True,
            capture_output=True,
            timeout=entry.get("timeout", 30),
            cwd=cwd,
            env=env,
        )
        if proc.returncode == 2:
            reason = proc.stderr.strip() or f"Blocked by {entry['plugin']}/{entry['script']}"
            return {"decision": "deny", "reason": reason}
        if proc.returncode == 0:
            parsed = parse_hook_decision(proc.stdout)
            if parsed:
                return parsed
        # Other return codes fail open per spec
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"warning: hook {entry['plugin']}/{entry['script']} timed out\n")
    except Exception as e:
        sys.stderr.write(f"warning: hook {entry['plugin']}/{entry['script']} failed: {e}\n")

    return {"decision": "allow"}


def handle_pre_tool_use(payload: dict, manifest: dict) -> dict:
    tool_call = payload.get("toolCall") or {}
    tool_name = tool_call.get("name") or payload.get("tool_name") or ""
    args = tool_call.get("args") or payload.get("tool_input") or {}
    command = args.get("CommandLine") or args.get("command") or ""
    conv_id = payload.get("conversationId") or payload.get("session_id") or ""
    workspaces = payload.get("workspacePaths", [])
    cwd = workspaces[0] if workspaces else payload.get("cwd") or os.getcwd()

    if tool_name != "run_command" or not command:
        return {"decision": "allow"}

    here = Path(__file__).resolve().parent
    repo_root = Path(manifest.get("repo_root", str(here)))

    # Step 1: Check Claude Code variable emulation
    claude_vars = resolve_claude_vars(command, repo_root, conv_id)
    overwrite_cmd = None
    if claude_vars:
        exports = " ".join(f"{k}='{v}'" for k, v in sorted(claude_vars.items()))
        export_line = f"export {exports}"
        overwrite_cmd = f"{export_line}\n{command}"

    # Step 2: Run safety hooks
    hooks = manifest.get("hooks", [])
    effective_cmd = overwrite_cmd if overwrite_cmd else command

    for entry in hooks:
        if entry.get("event") != "PreToolUse":
            continue
        plugin = entry["plugin"]
        script = entry["script"]
        script_path = here / "hook-scripts" / plugin / "hooks" / script
        plugin_root = here / "hook-scripts" / plugin

        result = run_single_hook(entry, script_path, plugin_root, effective_cmd, conv_id, cwd)
        if result.get("decision") in ("deny", "ask"):
            return result

    if overwrite_cmd:
        return {
            "decision": "allow",
            "overwrite": {"CommandLine": overwrite_cmd},
        }

    return {"decision": "allow"}


def main():
    try:
        raw_input = sys.stdin.read()
        payload = json.loads(raw_input) if raw_input.strip() else {}
    except Exception:
        payload = {}

    event_type = sys.argv[1] if len(sys.argv) > 1 else "pre-tool-use"
    manifest = load_manifest()

    if event_type == "pre-tool-use":
        result = handle_pre_tool_use(payload, manifest)
        print(json.dumps(result))
    else:
        print(json.dumps({}))

    sys.exit(0)


if __name__ == "__main__":
    main()
'''


def main(repo_root: Path, out_dir: Path, allow_extra: set[str]) -> int:
    allowlist = dict(AGY_SAFETY_ALLOWLIST)
    for extra in allow_extra:
        allowlist[extra] = "explicitly allowed via --allow"

    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_entries = []
    scripts_to_copy = {}
    scanned_plugins = set()

    for plugin_name, plugin_dir, label, manifest in discover_manifests(repo_root):
        scanned_plugins.add(plugin_name)
        hooks_dict = manifest.get("hooks", {})
        for event, groups in hooks_dict.items():
            if event != "PreToolUse":
                continue
            for group in groups or []:
                raw_matcher = group.get("matcher", "")
                matcher_tokens = [
                    t.strip() for t in raw_matcher.split("|") if t.strip()
                ]
                # Matches if matcher includes Bash, run_command, is empty (all tools), or *
                if matcher_tokens and not any(
                    t in ("Bash", "run_command", "*", "") for t in matcher_tokens
                ):
                    continue
                for hook in group.get("hooks", []):
                    if hook.get("type", "command") != "command":
                        continue
                    cmd = hook.get("command", "")
                    m = COMMAND_RE.match(cmd)
                    if not m:
                        continue
                    script = m.group("script")
                    key = f"{plugin_name}/{script}"
                    if key not in allowlist:
                        continue
                    if not (plugin_dir / "hooks" / script).is_file():
                        continue

                    timeout = normalize_timeout(hook.get("timeout", 30))
                    manifest_entries.append(
                        {
                            "plugin": plugin_name,
                            "script": script,
                            "event": "PreToolUse",
                            "timeout": timeout,
                            "description": allowlist[key],
                        }
                    )
                    scripts_to_copy.setdefault(plugin_name, set()).add(script)

    copied_count, copied_libs = copy_scripts(repo_root, scripts_to_copy, out_dir)

    # Write hooks_manifest.json
    manifest_data = {
        "repo_root": str(repo_root),
        "hooks": manifest_entries,
    }
    (out_dir / "hooks_manifest.json").write_text(
        json.dumps(manifest_data, indent=2), encoding="utf-8"
    )

    # Write run-agy-hook.py
    runner_code = RUN_AGY_HOOK_PY_CONTENT.replace("__MARKER__", GENERATED_MARKER)
    runner_py = out_dir / "run-agy-hook.py"
    runner_py.write_text(runner_code, encoding="utf-8")
    runner_py.chmod(0o755)

    # Write run-agy-hook.sh wrapper
    runner_sh = out_dir / "run-agy-hook.sh"
    runner_sh.write_text(
        "#!/usr/bin/env bash\nset -euo pipefail\n"
        'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'exec python3 -u "$DIR/run-agy-hook.py" "$@"\n',
        encoding="utf-8",
    )
    runner_sh.chmod(0o755)

    # Write hooks.json
    hooks_json_data = {
        "claude-safety-hooks": {
            "PreToolUse": [
                {
                    "matcher": "run_command",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 -u ./run-agy-hook.py pre-tool-use",
                            "timeout": 60,
                        }
                    ],
                }
            ],
            "PostToolUse": [
                {
                    "matcher": "run_command",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 -u ./run-agy-hook.py post-tool-use",
                            "timeout": 30,
                        }
                    ],
                }
            ],
        }
    }
    (out_dir / "hooks.json").write_text(
        json.dumps(hooks_json_data, indent=2), encoding="utf-8"
    )

    print(f"HOOK_PLUGINS_SCANNED={len(scanned_plugins)}")
    print(f"EXPORTED_HOOKS={len(manifest_entries)}")
    print(f"COPIED_SCRIPTS={copied_count}")
    print(f"COPIED_LIBS={','.join(copied_libs) or '-'}")
    print("OUTPUT_HOOKS_JSON=hooks.json")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(
            "usage: generate-antigravity-hooks.py <repo_root> <out_dir> [--allow <plugin>/<script>]...",
            file=sys.stderr,
        )
        sys.exit(2)
    extra_allowed = set()
    idx = 3
    while idx < len(sys.argv):
        if sys.argv[idx] == "--allow" and idx + 1 < len(sys.argv):
            extra_allowed.add(sys.argv[idx + 1])
            idx += 2
        else:
            idx += 1
    sys.exit(
        main(Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve(), extra_allowed)
    )
