#!/usr/bin/env python3
"""Generate Antigravity CLI lifecycle hooks from Claude Code plugin manifests.

Antigravity CLI (agy) supports lifecycle hooks via `hooks.json` in
`~/.gemini/config/hooks.json` (global) or `<workspace>/.agents/hooks.json` (project).

This generator projects the safety subset of Claude Code hooks into an Antigravity
hook suite:
  <plugin>/hooks.json                    \
  <plugin>/.claude-plugin/plugin.json#hooks > <out>/hooks.json + <out>/run-agy-hook.py
  <plugin>/hooks/<script>.sh              -> <out>/hook-scripts/<plugin>/hooks/

Contract:
  - PreToolUse on `run_command`:
      1. Claude Code variable emulation:
         Inspects `CommandLine` for `${CLAUDE_SKILL_DIR}`, `${CLAUDE_PLUGIN_ROOT}`,
         and `${CLAUDE_SESSION_ID}`. If present, resolves them against this
         checkout's skills and emits an `overwrite: { CommandLine: "export ...\n<cmd>" }`.
         A variable that does not resolve to exactly one directory -> `deny`
         with the candidates, never a guess.
      2. Safety gate evaluation:
         Evaluates matching safety hooks (branch protection, secret protection,
         repo deletion guards, etc.). Exit 2, hookSpecificOutput.permissionDecision
         "deny" or decision "block" -> `decision: "deny"`; permissionDecision
         "ask" -> `decision: "ask"`; updatedInput.command -> `deny` with the
         rewritten command in the reason (Antigravity documents no rewrite).
  - A script failure, missing script, or timeout FAILS OPEN (logs warning, allows).

Usage: generate-antigravity-hooks.py <repo_root> <out_dir> [--allow <plugin>/<script>]...
"""

import importlib.util
import json
import shlex
import sys
from pathlib import Path

# Manifest discovery, script/lib copying, the command shape and the safety
# allowlist are shared with the pi hook generator (which itself imports from
# the OpenCode one), so the three exports read manifests identically and a
# change to the allowlist lands in one place.
_PI_PATH = Path(__file__).with_name("generate-pi-hook-extension.py")
_spec = importlib.util.spec_from_file_location("pi_hooks", _PI_PATH)
_pi = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_pi)
COMMAND_RE = _pi.COMMAND_RE
normalize_timeout = _pi.normalize_timeout
discover_manifests = _pi.discover_manifests
copy_scripts = _pi.copy_scripts
# Only PreToolUse entries are exported, so the pi allowlist's SessionStart
# probes (drift-aggregator, git-drift-probe) never match here.
AGY_SAFETY_ALLOWLIST = _pi.PI_SAFETY_ALLOWLIST

GENERATED_MARKER = "Generated by scripts/generate-antigravity-hooks.py"


RUN_AGY_HOOK_PY_CONTENT = r'''#!/usr/bin/env python3
"""Antigravity CLI hook runner for Claude Code safety hooks and variable rewriting.
__MARKER__
"""

import hashlib
import json
import os
import re
import shlex
import subprocess
import sys
from pathlib import Path

SKILL_DIR_REF = re.compile(r"\$\{CLAUDE_SKILL_DIR\}|\$CLAUDE_SKILL_DIR(?![A-Za-z0-9_])")
PLUGIN_ROOT_REF = re.compile(r"\$\{CLAUDE_PLUGIN_ROOT\}|\$CLAUDE_PLUGIN_ROOT(?![A-Za-z0-9_])")
SESSION_ID_REF = re.compile(r"\$\{CLAUDE_SESSION_ID(?:[}:])|\$CLAUDE_SESSION_ID(?![A-Za-z0-9_])")

SKILL_DIR_PATH_REF = re.compile(
    r"(?:\$\{CLAUDE_SKILL_DIR\}|\$CLAUDE_SKILL_DIR(?![A-Za-z0-9_]))/([^\s\"'`;|&<>()]+)"
)
PLUGIN_ROOT_PATH_REF = re.compile(
    r"(?:\$\{CLAUDE_PLUGIN_ROOT\}|\$CLAUDE_PLUGIN_ROOT(?![A-Za-z0-9_]))/([^\s\"'`;|&<>()]+)"
)


def load_manifest():
    here = Path(__file__).resolve().parent
    manifest_file = here / "hooks_manifest.json"
    if manifest_file.is_file():
        try:
            return json.loads(manifest_file.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"hooks": [], "repo_root": str(here)}


def extract_rel_paths(command: str, pattern: re.Pattern) -> list[str]:
    rels = set()
    for match in pattern.finditer(command):
        rel = match.group(1).rstrip("/")
        if rel and not re.search(r"[\$*?\[\]{}]", rel):
            rels.add(rel)
    return sorted(rels)


def plugin_skill_dirs(repo_root: Path):
    for p_dir in sorted(repo_root.glob("*-plugin")):
        skills_base = p_dir / "skills"
        if skills_base.is_dir():
            for s_dir in sorted(skills_base.iterdir()):
                if s_dir.is_dir():
                    yield p_dir, s_dir


def describe_candidates(var: str, rels: list[str], candidates: list[Path]) -> str:
    if not rels:
        return (
            f"${{{var}}} is used without a path after it, so it cannot be resolved "
            "to one directory under Antigravity. Use the absolute path instead."
        )
    if not candidates:
        return (
            f"No directory in this checkout contains {', '.join(rels)}, so "
            f"${{{var}}} cannot be resolved. Use the absolute path instead."
        )
    shown = "\n".join(f"  {c}" for c in candidates[:5])
    more = f"\n  ... and {len(candidates) - 5} more" if len(candidates) > 5 else ""
    return (
        f"${{{var}}}/{rels[0]} matches {len(candidates)} directories, so it is "
        f"ambiguous. Re-run with the absolute path of the intended one:\n{shown}{more}"
    )


def resolve_claude_vars(command: str, repo_root: Path, conversation_id: str) -> tuple[dict[str, str], str]:
    """Return (exports, error). A variable that does not resolve to exactly one
    directory is an error, never a guess: a wrong or empty path would run some
    other skill's script, or a path rooted at /."""
    needed = {}
    has_skill_dir = bool(SKILL_DIR_REF.search(command))
    has_plugin_root = bool(PLUGIN_ROOT_REF.search(command))
    has_session_id = bool(SESSION_ID_REF.search(command))

    skill_rels = extract_rel_paths(command, SKILL_DIR_PATH_REF)
    plugin_rels = extract_rel_paths(command, PLUGIN_ROOT_PATH_REF)

    if has_skill_dir:
        candidates = [
            s_dir
            for p_dir, s_dir in plugin_skill_dirs(repo_root)
            if skill_rels
            and all((s_dir / rel).exists() for rel in skill_rels)
            and all((p_dir / rel).exists() for rel in plugin_rels)
        ]
        if len(candidates) != 1:
            return {}, describe_candidates("CLAUDE_SKILL_DIR", skill_rels, candidates)
        needed["CLAUDE_SKILL_DIR"] = str(candidates[0])
        if has_plugin_root:
            needed["CLAUDE_PLUGIN_ROOT"] = str(candidates[0].parent.parent)
    elif has_plugin_root:
        candidates = [
            p_dir
            for p_dir in sorted(repo_root.glob("*-plugin"))
            if plugin_rels and all((p_dir / rel).exists() for rel in plugin_rels)
        ]
        if len(candidates) != 1:
            return {}, describe_candidates("CLAUDE_PLUGIN_ROOT", plugin_rels, candidates)
        needed["CLAUDE_PLUGIN_ROOT"] = str(candidates[0])

    if has_session_id:
        needed["CLAUDE_SESSION_ID"] = hashlib.sha256(conversation_id.encode("utf-8")).hexdigest()[:16]

    return needed, ""


def parse_hook_decision(stdout_str: str, who: str) -> dict:
    """Map a Claude Code hook's JSON output to an Antigravity decision.

    Claude Code hooks put the PreToolUse verdict in
    hookSpecificOutput.permissionDecision (+ permissionDecisionReason); a
    top-level decision "block" is the older form. updatedInput.command is a
    rewrite: Antigravity documents no way for a hook to rewrite a command, so
    the call is denied and the rewritten command handed back in the reason.
    Denying is the fail-safe direction: a dropped rewrite would run the
    original (e.g. a real kubectl apply instead of its dry run).
    """
    trimmed = stdout_str.strip()
    if not trimmed.startswith("{"):
        return {}
    try:
        data = json.loads(trimmed)
    except ValueError:
        return {}
    if not isinstance(data, dict):
        return {}
    hso = data.get("hookSpecificOutput")
    hso = hso if isinstance(hso, dict) else {}
    perm = hso.get("permissionDecision")
    reason = hso.get("permissionDecisionReason") or data.get("reason") or ""
    if perm == "deny" or data.get("decision") == "block":
        return {"decision": "deny", "reason": reason or f"Blocked by {who}"}
    if perm == "ask":
        return {"decision": "ask", "reason": reason or f"{who} asks for confirmation."}
    updated = hso.get("updatedInput")
    if isinstance(updated, dict) and isinstance(updated.get("command"), str):
        msg = (
            f"{who} rewrites this command, and Antigravity hooks cannot rewrite a "
            f"command, so it was blocked. Run the rewritten command instead:\n"
            f"{updated['command']}"
        )
        if reason:
            msg += f"\n\nHook note: {reason}"
        return {"decision": "deny", "reason": msg}
    return {}


def run_single_hook(entry: dict, script_path: Path, plugin_root: Path, command: str, conv_id: str, cwd: str) -> dict:
    """Execute a single shell safety hook."""
    if not script_path.is_file():
        return {"decision": "allow"}

    payload = {
        "tool_name": "Bash",
        "tool_input": {"command": command},
        "session_id": conv_id,
        "cwd": cwd,
    }

    env = os.environ.copy()
    env["CLAUDE_PLUGIN_ROOT"] = str(plugin_root)

    try:
        proc = subprocess.run(
            ["bash", str(script_path)],
            input=json.dumps(payload),
            text=True,
            capture_output=True,
            timeout=entry.get("timeout", 30),
            cwd=cwd,
            env=env,
        )
        if proc.returncode == 2:
            reason = proc.stderr.strip() or f"Blocked by {entry['plugin']}/{entry['script']}"
            return {"decision": "deny", "reason": reason}
        if proc.returncode == 0:
            parsed = parse_hook_decision(proc.stdout, f"{entry['plugin']}/{entry['script']}")
            if parsed:
                return parsed
        # Other return codes fail open per spec
    except subprocess.TimeoutExpired:
        sys.stderr.write(f"warning: hook {entry['plugin']}/{entry['script']} timed out\n")
    except Exception as e:
        sys.stderr.write(f"warning: hook {entry['plugin']}/{entry['script']} failed: {e}\n")

    return {"decision": "allow"}


def handle_pre_tool_use(payload: dict, manifest: dict) -> dict:
    tool_call = payload.get("toolCall") or {}
    tool_name = tool_call.get("name") or payload.get("tool_name") or ""
    args = tool_call.get("args") or payload.get("tool_input") or {}
    command = args.get("CommandLine") or args.get("command") or ""
    conv_id = payload.get("conversationId") or payload.get("session_id") or ""
    workspaces = payload.get("workspacePaths", [])
    cwd = workspaces[0] if workspaces else payload.get("cwd") or os.getcwd()

    if tool_name != "run_command" or not command:
        return {"decision": "allow"}

    here = Path(__file__).resolve().parent
    repo_root = Path(manifest.get("repo_root", str(here)))

    # Step 1: Check Claude Code variable emulation
    claude_vars, var_error = resolve_claude_vars(command, repo_root, conv_id)
    if var_error:
        return {"decision": "deny", "reason": var_error}
    overwrite_cmd = None
    if claude_vars:
        exports = " ".join(f"{k}={shlex.quote(v)}" for k, v in sorted(claude_vars.items()))
        export_line = f"export {exports}"
        overwrite_cmd = f"{export_line}\n{command}"

    # Step 2: Run safety hooks
    hooks = manifest.get("hooks", [])
    effective_cmd = overwrite_cmd if overwrite_cmd else command

    for entry in hooks:
        if entry.get("event") != "PreToolUse":
            continue
        plugin = entry["plugin"]
        script = entry["script"]
        script_path = here / "hook-scripts" / plugin / "hooks" / script
        plugin_root = here / "hook-scripts" / plugin

        result = run_single_hook(entry, script_path, plugin_root, effective_cmd, conv_id, cwd)
        if result.get("decision") in ("deny", "ask"):
            return result

    if overwrite_cmd:
        return {
            "decision": "allow",
            "overwrite": {"CommandLine": overwrite_cmd},
        }

    return {"decision": "allow"}


def main():
    try:
        raw_input = sys.stdin.read()
        payload = json.loads(raw_input) if raw_input.strip() else {}
    except Exception:
        payload = {}

    event_type = sys.argv[1] if len(sys.argv) > 1 else "pre-tool-use"
    manifest = load_manifest()

    if event_type == "pre-tool-use":
        result = handle_pre_tool_use(payload, manifest)
        print(json.dumps(result))
    else:
        print(json.dumps({}))

    sys.exit(0)


if __name__ == "__main__":
    main()
'''


def main(repo_root: Path, out_dir: Path, allow_extra: set[str]) -> int:
    allowlist = dict(AGY_SAFETY_ALLOWLIST)
    for extra in allow_extra:
        allowlist[extra] = "explicitly allowed via --allow"

    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_entries = []
    scripts_to_copy = {}
    scanned_plugins = set()

    for plugin_dir, _label, manifest in discover_manifests(repo_root):
        plugin_name = plugin_dir.name
        scanned_plugins.add(plugin_name)
        hooks_dict = manifest.get("hooks", {})
        for event, groups in hooks_dict.items():
            if event != "PreToolUse":
                continue
            for group in groups or []:
                raw_matcher = group.get("matcher", "")
                matcher_tokens = [
                    t.strip() for t in raw_matcher.split("|") if t.strip()
                ]
                # Matches if matcher includes Bash, run_command, is empty (all tools), or *
                if matcher_tokens and not any(
                    t in ("Bash", "run_command", "*", "") for t in matcher_tokens
                ):
                    continue
                for hook in group.get("hooks", []):
                    if hook.get("type", "command") != "command":
                        continue
                    cmd = hook.get("command", "")
                    m = COMMAND_RE.match(cmd)
                    if not m:
                        continue
                    script = m.group("script")
                    key = f"{plugin_name}/{script}"
                    if key not in allowlist:
                        continue
                    if not (plugin_dir / "hooks" / script).is_file():
                        continue

                    timeout = normalize_timeout(hook.get("timeout", 30))
                    manifest_entries.append(
                        {
                            "plugin": plugin_name,
                            "script": script,
                            "event": "PreToolUse",
                            "timeout": timeout,
                            "description": allowlist[key],
                        }
                    )
                    scripts_to_copy.setdefault(plugin_name, set()).add(script)

    copied_count, copied_libs = copy_scripts(repo_root, scripts_to_copy, out_dir)

    # Write hooks_manifest.json
    manifest_data = {
        "repo_root": str(repo_root),
        "hooks": manifest_entries,
    }
    (out_dir / "hooks_manifest.json").write_text(
        json.dumps(manifest_data, indent=2), encoding="utf-8"
    )

    # Write run-agy-hook.py
    runner_code = RUN_AGY_HOOK_PY_CONTENT.replace("__MARKER__", GENERATED_MARKER)
    runner_py = out_dir / "run-agy-hook.py"
    runner_py.write_text(runner_code, encoding="utf-8")
    runner_py.chmod(0o755)

    # Write run-agy-hook.sh wrapper
    runner_sh = out_dir / "run-agy-hook.sh"
    runner_sh.write_text(
        "#!/usr/bin/env bash\nset -euo pipefail\n"
        'DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"\n'
        'exec python3 -u "$DIR/run-agy-hook.py" "$@"\n',
        encoding="utf-8",
    )
    runner_sh.chmod(0o755)

    # Write hooks.json. The runner is addressed by absolute path: Antigravity
    # does not document the working directory a hook command runs in, and a
    # relative path would resolve against the workspace. install-antigravity.sh
    # rewrites this path to the install target. Only PreToolUse is registered;
    # the runner has nothing to do after a tool runs.
    runner_cmd = f"python3 -u {shlex.quote(str(runner_py))} pre-tool-use"
    hooks_json_data = {
        "claude-safety-hooks": {
            "PreToolUse": [
                {
                    "matcher": "run_command",
                    "hooks": [
                        {"type": "command", "command": runner_cmd, "timeout": 60}
                    ],
                }
            ],
        }
    }
    (out_dir / "hooks.json").write_text(
        json.dumps(hooks_json_data, indent=2), encoding="utf-8"
    )

    print(f"HOOK_PLUGINS_SCANNED={len(scanned_plugins)}")
    print(f"EXPORTED_HOOKS={len(manifest_entries)}")
    print(f"COPIED_SCRIPTS={copied_count}")
    print(f"COPIED_LIBS={','.join(copied_libs) or '-'}")
    print("OUTPUT_HOOKS_JSON=hooks.json")
    return 0


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(
            "usage: generate-antigravity-hooks.py <repo_root> <out_dir> [--allow <plugin>/<script>]...",
            file=sys.stderr,
        )
        sys.exit(2)
    extra_allowed = set()
    idx = 3
    while idx < len(sys.argv):
        if sys.argv[idx] == "--allow" and idx + 1 < len(sys.argv):
            extra_allowed.add(sys.argv[idx + 1])
            idx += 2
        else:
            idx += 1
    sys.exit(
        main(Path(sys.argv[1]).resolve(), Path(sys.argv[2]).resolve(), extra_allowed)
    )
