#!/usr/bin/env python3
"""Generate a pi extension that runs the marketplace's Claude Code safety hooks.

pi (pi.dev) never evaluates a Claude Code hook manifest, so every PreToolUse /
PostToolUse / SessionStart command hook is inert under pi (issue #2634). This
generator projects the SAFETY subset into one pi extension that registers
`pi.on(...)` handlers and runs the original shell scripts unchanged:

  <plugin>/hooks.json                      \\
  <plugin>/.claude-plugin/plugin.json#hooks  >  <out>/extensions/plugin-hooks/index.ts
  <plugin>/hooks/<script>.sh              ->  <out>/extensions/plugin-hooks/hook-scripts/<plugin>/hooks/

Manifest discovery reads BOTH declaration sites. Eight plugins declare their
hooks inline in `.claude-plugin/plugin.json` with no hooks.json, hooks-plugin
among them — and hooks-plugin holds the safety guards. A glob over
`*-plugin/hooks.json` alone (the OpenCode generator's shape, tracked in #2724)
would export none of them.

Event mapping (pi 0.84 extension API, docs/extensions.md):
  PreToolUse   -> pi.on("tool_call"):   exit 2 or JSON permissionDecision
                  "deny" -> { block: true, reason }; "ask" -> ctx.ui.confirm()
                  when pi has a UI, block otherwise; updatedInput.command is
                  applied to a bash call.
  PostToolUse  -> pi.on("tool_result"): exit-2 stderr / JSON block reason /
                  additionalContext appended to the tool result content.
  SessionStart -> pi.on("session_start"): additionalContext (or plain stdout)
                  queued with pi.sendMessage(..., { deliverAs: "nextTurn" }).

Scope: only hooks named in PI_SAFETY_ALLOWLIST are exported. Style nudges,
loggers and cues are skipped BY NAME and reported, because a nudge phrased for
Claude Code's tools is noise on another harness (maintainer scoping, #2634;
session-plugin's two nudges are tracked in #2661). `--allow <plugin>/<script>`
adds an entry for one run (opt-in, and the test seam).

Skipped, loudly (reported on stdout and in the generated header):
  - prompt / agent hooks (pi has no model-evaluation hook),
  - events with no pi equivalent (Stop, PreCompact, PermissionRequest, ...),
  - matchers naming only tools pi does not have (Workflow, Skill, ...),
  - hooks not in the safety allowlist,
  - command strings not shaped `bash ${CLAUDE_PLUGIN_ROOT}/hooks/<script>.sh`,
  - referenced scripts that do not exist.

A script missing or crashing at RUN time fails open (console.error + allow),
the same contract as the OpenCode export.

Usage: generate-pi-hook-extension.py <repo_root> <out_dir> [--allow <plugin>/<script>]...
"""

import importlib.util
import json
import re
import shutil
import sys
from pathlib import Path

# glob_to_regex / normalize_timeout / the command and matcher shapes are shared
# with the OpenCode hook generator; importing them keeps the two exports parsing
# manifests identically instead of drifting apart.
_OC_PATH = Path(__file__).with_name("generate-opencode-hook-plugins.py")
_spec = importlib.util.spec_from_file_location("opencode_hooks", _OC_PATH)
_oc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_oc)
glob_to_regex = _oc.glob_to_regex
normalize_timeout = _oc.normalize_timeout
COMMAND_RE = _oc.COMMAND_RE
MATCHER_WITH_ARG_RE = _oc.MATCHER_WITH_ARG_RE

EXTENSION_NAME = "plugin-hooks"
GENERATED_MARKER = "Generated by scripts/generate-pi-hook-extension.py"

EXPORTABLE_EVENTS = {
    "PreToolUse": "tool_call",
    "PostToolUse": "tool_result",
    "SessionStart": "session_start",
}

# Claude Code tool name -> pi built-in tool name (pi 0.84 ships these seven).
CLAUDE_TO_PI_TOOL = {
    "Bash": "bash",
    "Read": "read",
    "Write": "write",
    "Edit": "edit",
    "Glob": "find",
    "Grep": "grep",
    "LS": "ls",
}

# Hooks exported to pi, keyed <plugin>/<script>. Safety, integrity and
# drift-prevention guards only (#2634). Anything absent is skipped by name.
# Deliberately absent, not merely unclassified:
#   hooks-plugin/bash-antipatterns.sh — safety blocks mixed with style blocks
#     whose remedy names Claude Code's Read/Grep tools (#2788).
#   hooks-plugin/auto-checkpoint.sh — its stash entries are surfaced only by
#     the Stop hook git-stash-reminder.sh, and Stop has no pi mapping here.
#   session-plugin's spinup/end nudges — tracked in #2661.
PI_SAFETY_ALLOWLIST = {
    "hooks-plugin/branch-protection.sh": "blocks commits and pushes on the default branch",
    "hooks-plugin/secret-protection.sh": "blocks reads/writes of credential files and env dumps",
    "hooks-plugin/repo-deletion-safety.sh": "blocks rm -rf of a repo with unpushed work",
    "hooks-plugin/external-pr-merge-guard.sh": "blocks merging a PR authored outside the owner/bots",
    "hooks-plugin/branch-base-guard.sh": "confirms before branching off a stale base",
    "hooks-plugin/drift-aggregator.sh": "delivers the drift probes' consolidated SessionStart findings",
    "git-plugin/validate-pr-issue-links.sh": "validates issue-closing keywords before a PR is created",
    "git-plugin/check-pr-metadata-on-push.sh": "blocks a push that leaves the open PR's metadata stale",
    "git-plugin/check-branch-sync-on-push.sh": "confirms before committing onto a merged or behind branch",
    "git-plugin/git-drift-probe.sh": "records branch drift at session start for the aggregator",
    "terraform-plugin/validate-terraform-apply.sh": "blocks terraform apply -auto-approve / without a saved plan",
    "kubernetes-plugin/validate-kubectl-context.sh": "blocks mutating kubectl without an explicit --context",
    "kubernetes-plugin/inject-kubectl-dry-run.sh": "rewrites mutating kubectl to --dry-run=client first",
    "feedback-plugin/check-open-pr.sh": "blocks an unconditional force-push to a branch with an open PR",
}

# Scripts that consume what sibling SessionStart hooks write in the same event,
# so they must run after them. drift-aggregator.sh reads the signal files the
# drift probes emit (hooks-plugin/hooks/lib/drift-protocol.sh).
RUN_LAST = {"drift-aggregator.sh"}

CROSS_PLUGIN_LIB_RE = re.compile(r"([A-Za-z0-9_-]+-plugin)/hooks/lib/")


def discover_manifests(repo_root):
    """Yield (plugin_dir, source_label, manifest_dict) for every hook manifest.

    Reads `<plugin>/hooks.json` AND `<plugin>/.claude-plugin/plugin.json#hooks`.
    A plugin.json `hooks` value that is a path (or list of paths) is resolved
    relative to the plugin dir and de-duplicated against hooks.json, so a
    `"hooks": "./hooks.json"` pointer is not read twice.
    """
    for plugin_dir in sorted(p for p in repo_root.glob("*-plugin") if p.is_dir()):
        seen = set()
        hooks_json = plugin_dir / "hooks.json"
        if hooks_json.is_file():
            seen.add(hooks_json.resolve())
            yield plugin_dir, "hooks.json", json.loads(hooks_json.read_text())
        plugin_json = plugin_dir / ".claude-plugin" / "plugin.json"
        if not plugin_json.is_file():
            continue
        declared = json.loads(plugin_json.read_text()).get("hooks")
        if isinstance(declared, dict):
            yield plugin_dir, "plugin.json", {"hooks": declared}
            continue
        refs = declared if isinstance(declared, list) else [declared]
        for ref in refs:
            if not isinstance(ref, str):
                continue
            target = (plugin_dir / ref).resolve()
            if target in seen or not target.is_file():
                continue
            seen.add(target)
            label = target.relative_to(plugin_dir.resolve()).as_posix()
            yield plugin_dir, label, json.loads(target.read_text())


def parse_tool_matcher(matcher):
    """Return (entries, unmapped): entries are {tool, pathRe} per `|` alternative
    pi can match; unmapped lists alternatives naming a tool pi does not have."""
    matcher = (matcher or "").strip()
    if matcher in ("", "*"):
        return [{"tool": None, "pathRe": None}], []
    alternatives = matcher.split("|") if "(" not in matcher else [matcher]
    entries, unmapped = [], []
    for alt in (a.strip() for a in alternatives):
        m = MATCHER_WITH_ARG_RE.match(alt)
        if m:
            tool = CLAUDE_TO_PI_TOOL.get(m.group(1))
            if tool in ("read", "write", "edit"):
                entries.append({"tool": tool, "pathRe": glob_to_regex(m.group(2))})
            else:
                unmapped.append(alt)
        elif alt.startswith("mcp__"):
            # MCP tools keep their Claude name; a pi MCP bridge may expose them.
            entries.append({"tool": alt, "pathRe": None})
        elif alt in CLAUDE_TO_PI_TOOL:
            entries.append({"tool": CLAUDE_TO_PI_TOOL[alt], "pathRe": None})
        else:
            unmapped.append(alt)
    return entries, unmapped


def collect(repo_root, allowlist):
    """Walk every manifest; return (plugins, tool_call, tool_result,
    session_start, skipped, notes, scripts) where scripts maps plugin -> set."""
    plugins = {}
    slots = {"tool_call": [], "tool_result": [], "session_start": []}
    skipped, notes = [], []
    scripts = {}

    for plugin_dir, source, manifest in discover_manifests(repo_root):
        plugin = plugin_dir.name
        stats = plugins.setdefault(plugin, {"sources": [], "exported": 0, "skipped": 0})
        stats["sources"].append(source)

        def skip(event, matcher, kind, reason, script="-"):
            skipped.append((plugin, event, matcher, kind, script, reason))
            stats["skipped"] += 1

        for event, groups in (manifest.get("hooks") or {}).items():
            slot = EXPORTABLE_EVENTS.get(event)
            for group in groups or []:
                matcher = group.get("matcher", "")
                for hook in group.get("hooks", []):
                    kind = hook.get("type", "command")
                    cmd = (hook.get("command") or "").strip()
                    m = COMMAND_RE.match(cmd) if kind == "command" else None
                    script = m.group(1) if m else "-"
                    if slot is None:
                        skip(
                            event,
                            matcher,
                            kind,
                            "no pi equivalent for this event",
                            script,
                        )
                        continue
                    if kind != "command":
                        skip(event, matcher, kind, "pi has no model-evaluation hook")
                        continue
                    if not m:
                        skip(event, matcher, kind, f"unparseable command: {cmd}")
                        continue
                    key = f"{plugin}/{script}"
                    if key not in allowlist:
                        skip(
                            event,
                            matcher,
                            kind,
                            "not in the pi safety allowlist (#2634)",
                            script,
                        )
                        continue
                    if not (plugin_dir / "hooks" / script).is_file():
                        skip(
                            event,
                            matcher,
                            kind,
                            f"referenced script missing: hooks/{script}",
                            script,
                        )
                        continue
                    timeout = normalize_timeout(hook.get("timeout", 60))
                    if slot == "session_start":
                        sources = [s.strip() for s in matcher.split("|") if s.strip()]
                        slots[slot].append(
                            {
                                "plugin": plugin,
                                "script": script,
                                "sources": sources,
                                "timeout": timeout,
                                "last": script in RUN_LAST,
                            }
                        )
                    else:
                        entries, unmapped = parse_tool_matcher(matcher)
                        if not entries:
                            skip(
                                event,
                                matcher,
                                kind,
                                "no pi tool for matcher: " + "|".join(unmapped),
                                script,
                            )
                            continue
                        if unmapped:
                            notes.append(
                                (
                                    plugin,
                                    event,
                                    matcher,
                                    script,
                                    "unmapped alternatives: " + "|".join(unmapped),
                                )
                            )
                        for entry in entries:
                            slots[slot].append(
                                {
                                    "plugin": plugin,
                                    "script": script,
                                    **entry,
                                    "timeout": timeout,
                                }
                            )
                    stats["exported"] += 1
                    scripts.setdefault(plugin, set()).add(script)

    slots["session_start"].sort(key=lambda e: e["last"])
    return plugins, slots, skipped, notes, scripts


def copy_scripts(repo_root, scripts, ext_dir):
    """Copy each exported script plus the hooks/lib dirs it sources (own plugin's
    when it mentions lib/, and any <plugin>/hooks/lib it reaches across)."""
    copied = 0
    libs = set()
    for plugin, names in scripts.items():
        for name in sorted(names):
            src = repo_root / plugin / "hooks" / name
            dst = ext_dir / "hook-scripts" / plugin / "hooks" / name
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            copied += 1
            text = src.read_text(errors="replace")
            if "/lib/" in text and (repo_root / plugin / "hooks" / "lib").is_dir():
                libs.add(plugin)
            libs.update(
                p
                for p in CROSS_PLUGIN_LIB_RE.findall(text)
                if (repo_root / p / "hooks" / "lib").is_dir()
            )
    for plugin in sorted(libs):
        dst = ext_dir / "hook-scripts" / plugin / "hooks" / "lib"
        shutil.copytree(repo_root / plugin / "hooks" / "lib", dst, dirs_exist_ok=True)
    return copied, sorted(libs)


TS_TEMPLATE = r"""// __MARKER__ — DO NOT EDIT.
// Claude Code safety hooks -> pi extension (issue #2634). Regenerate with
// `just export-pi-hooks`; install with `just install-pi-hooks`.
//
// Plain JavaScript in a .ts file on purpose: pi transpiles it, and a plain-JS
// body also runs under bare `node`, which is how scripts/tests/ exercises it.
//
// Semantics:
//   PreToolUse   -> tool_call     exit 2 / JSON deny -> { block: true, reason }
//                                 JSON ask -> ctx.ui.confirm() (block without a UI)
//                                 updatedInput.command -> rewrites a bash call
//   PostToolUse  -> tool_result   exit-2 stderr / block reason / additionalContext
//                                 appended to the tool result content
//   SessionStart -> session_start additionalContext (or stdout) queued for the
//                                 next turn via pi.sendMessage
//   A missing, crashing or timed-out script FAILS OPEN (console.error + allow).
__SKIP_REPORT__
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPTS_ROOT = join(dirname(fileURLToPath(import.meta.url)), "hook-scripts");

const TOOL_CALL = __TOOL_CALL__;

const TOOL_RESULT = __TOOL_RESULT__;

const SESSION_START = __SESSION_START__;

// pi tool name -> Claude Code tool name (what the scripts expect on stdin).
const CLAUDE_TOOL_NAMES = {
  bash: "Bash", read: "Read", write: "Write", edit: "Edit",
  find: "Glob", grep: "Grep", ls: "LS",
};

const LABEL = "[plugin-hooks]";

function claudeToolName(tool) {
  return CLAUDE_TOOL_NAMES[tool] ?? tool;
}

function absPath(p, cwd) {
  if (typeof p !== "string" || p === "") return "";
  if (p === "~" || p.startsWith("~/")) return join(homedir(), p.slice(1));
  return isAbsolute(p) ? p : resolve(cwd, p);
}

// pi inputs use `path` and edits[].oldText/newText; Claude hook payloads use
// snake_case `file_path` and a single old_string/new_string. Multi-edits are
// joined so content-scanning hooks still see every replacement.
function toToolInput(tool, input, cwd) {
  const out = { ...(input ?? {}) };
  if (typeof out.path === "string") out.file_path = absPath(out.path, cwd);
  if (tool === "edit" && Array.isArray(out.edits)) {
    out.old_string = out.edits.map((e) => e?.oldText ?? "").join("\n");
    out.new_string = out.edits.map((e) => e?.newText ?? "").join("\n");
    out.edits = out.edits.map((e) => ({ old_string: e?.oldText ?? "", new_string: e?.newText ?? "" }));
  }
  return out;
}

function matches(entry, tool, input, cwd) {
  if (entry.tool !== null && entry.tool !== tool) return false;
  if (entry.pathRe) {
    const p = absPath(input?.path, cwd);
    if (p === "") return false;
    if (!new RegExp(entry.pathRe).test(relative(cwd, p))) return false;
  }
  return true;
}

function parseDecision(stdout) {
  const t = (stdout ?? "").trim();
  if (!t.startsWith("{")) return {};
  try {
    const j = JSON.parse(t);
    const hso = j.hookSpecificOutput ?? {};
    return {
      deny: hso.permissionDecision === "deny" || j.decision === "block",
      ask: hso.permissionDecision === "ask",
      reason: hso.permissionDecisionReason ?? j.reason ?? "",
      context: hso.additionalContext ?? "",
      updatedInput: hso.updatedInput ?? null,
    };
  } catch {
    return {};
  }
}

function runHook(entry, payload, cwd) {
  const script = join(SCRIPTS_ROOT, entry.plugin, "hooks", entry.script);
  if (!existsSync(script)) {
    console.error(`${LABEL} ${entry.plugin}/${entry.script}: script missing, allowing`);
    return Promise.resolve(null);
  }
  return new Promise((done) => {
    let stdout = "";
    let stderr = "";
    let settled = false;
    const finish = (value) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      done(value);
    };
    let child;
    try {
      child = spawn("bash", [script], {
        cwd,
        env: {
          ...process.env,
          CLAUDE_PLUGIN_ROOT: join(SCRIPTS_ROOT, entry.plugin),
          CLAUDE_PROJECT_DIR: cwd,
        },
        stdio: ["pipe", "pipe", "pipe"],
      });
    } catch (err) {
      console.error(`${LABEL} ${entry.plugin}/${entry.script}: ${err}`);
      done(null);
      return;
    }
    const timer = setTimeout(() => {
      console.error(`${LABEL} ${entry.plugin}/${entry.script}: timed out after ${entry.timeout}s, allowing`);
      child.kill("SIGKILL");
      finish(null);
    }, (entry.timeout ?? 60) * 1000);
    child.stdout.on("data", (d) => { stdout += d; });
    child.stderr.on("data", (d) => { stderr += d; });
    child.stdin.on("error", () => {});
    child.on("error", (err) => {
      console.error(`${LABEL} ${entry.plugin}/${entry.script}: ${err}`);
      finish(null);
    });
    child.on("close", (code) => finish({ exitCode: code ?? 1, stdout, stderr }));
    child.stdin.end(JSON.stringify(payload));
  });
}

function sessionIdOf(ctx) {
  try {
    return ctx?.sessionManager?.getSessionId?.() ?? "";
  } catch {
    return "";
  }
}

function textOf(content) {
  return (Array.isArray(content) ? content : [])
    .filter((c) => c?.type === "text")
    .map((c) => c.text ?? "")
    .join("\n");
}

function applyUpdatedInput(event, updated, entry) {
  if (event.toolName === "bash" && typeof updated?.command === "string") {
    event.input.command = updated.command;
    return;
  }
  console.error(`${LABEL} ${entry.plugin}/${entry.script}: updatedInput for ${event.toolName} is not mapped to pi; ignored`);
}

/** @param {import("@earendil-works/pi-coding-agent").ExtensionAPI} pi */
export default function pluginHooks(pi) {
  // Matching hooks run concurrently against the same payload, as Claude Code
  // runs them; results are then read in declaration order, so the first
  // block wins deterministically.
  if (TOOL_CALL.length) {
    pi.on("tool_call", async (event, ctx) => {
      const cwd = ctx?.cwd ?? process.cwd();
      const hits = TOOL_CALL.filter((entry) => matches(entry, event.toolName, event.input, cwd));
      if (!hits.length) return undefined;
      const payload = {
        hook_event_name: "PreToolUse",
        tool_name: claudeToolName(event.toolName),
        tool_input: toToolInput(event.toolName, event.input, cwd),
        session_id: sessionIdOf(ctx),
        cwd,
        transcript_path: "",
        permission_mode: "default",
      };
      const results = await Promise.all(hits.map((entry) => runHook(entry, payload, cwd)));
      for (const [i, entry] of hits.entries()) {
        const res = results[i];
        if (!res) continue;
        const who = `${entry.plugin}/${entry.script}`;
        if (res.exitCode === 2) {
          return { block: true, reason: res.stderr.trim() || `Blocked by ${who}` };
        }
        if (res.exitCode !== 0) {
          console.error(`${LABEL} ${who} exited ${res.exitCode}: ${res.stderr.trim()}`);
          continue;
        }
        const d = parseDecision(res.stdout);
        if (d.deny) return { block: true, reason: d.reason || `Blocked by ${who}` };
        if (d.ask) {
          const question = d.reason || `${who} asks for confirmation before this call.`;
          const ok = ctx?.hasUI ? await ctx.ui.confirm(who, question) : false;
          if (!ok) {
            return {
              block: true,
              reason: ctx?.hasUI
                ? `Declined: ${question}`
                : `${question}\n\n(${who} requires confirmation and pi has no interactive UI; blocked.)`,
            };
          }
        }
        if (d.updatedInput) applyUpdatedInput(event, d.updatedInput, entry);
      }
      return undefined;
    });
  }

  if (TOOL_RESULT.length) {
    pi.on("tool_result", async (event, ctx) => {
      const cwd = ctx?.cwd ?? process.cwd();
      const hits = TOOL_RESULT.filter((entry) => matches(entry, event.toolName, event.input, cwd));
      if (!hits.length) return undefined;
      const payload = {
        hook_event_name: "PostToolUse",
        tool_name: claudeToolName(event.toolName),
        tool_input: toToolInput(event.toolName, event.input, cwd),
        tool_response: { output: textOf(event.content), is_error: Boolean(event.isError) },
        session_id: sessionIdOf(ctx),
        cwd,
        transcript_path: "",
      };
      const results = await Promise.all(hits.map((entry) => runHook(entry, payload, cwd)));
      let content = Array.isArray(event.content) ? [...event.content] : [];
      let changed = false;
      for (const [i, entry] of hits.entries()) {
        const res = results[i];
        if (!res) continue;
        const notes = [];
        if (res.exitCode === 2) {
          if (res.stderr.trim()) notes.push(res.stderr.trim());
        } else if (res.exitCode === 0) {
          const d = parseDecision(res.stdout);
          if (d.deny && d.reason) notes.push(d.reason);
          if (d.context) notes.push(d.context);
        } else {
          console.error(`${LABEL} ${entry.plugin}/${entry.script} exited ${res.exitCode}: ${res.stderr.trim()}`);
        }
        if (notes.length) {
          content = [...content, { type: "text", text: `[${entry.script}] ` + notes.join("\n") }];
          changed = true;
        }
      }
      return changed ? { content } : undefined;
    });
  }

  if (SESSION_START.length) {
    pi.on("session_start", async (event, ctx) => {
      const cwd = ctx?.cwd ?? process.cwd();
      const reason = event?.reason ?? "startup";
      const source = reason === "new" ? "clear" : reason === "fork" ? "resume" : reason;
      const payload = {
        hook_event_name: "SessionStart",
        source,
        session_id: sessionIdOf(ctx),
        cwd,
        transcript_path: "",
      };
      const hits = SESSION_START.filter((e) => !e.sources.length || e.sources.includes(source));
      // `last` hooks consume what the others write in this same event, so they
      // start only once the first wave has finished.
      const first = hits.filter((e) => !e.last);
      const last = hits.filter((e) => e.last);
      const results = [
        ...(await Promise.all(first.map((e) => runHook(e, payload, cwd)))),
        ...(await Promise.all(last.map((e) => runHook(e, payload, cwd)))),
      ];
      const parts = [];
      for (const [i, entry] of [...first, ...last].entries()) {
        const res = results[i];
        if (!res) continue;
        if (res.exitCode !== 0) {
          console.error(`${LABEL} ${entry.plugin}/${entry.script} exited ${res.exitCode}: ${res.stderr.trim()}`);
          continue;
        }
        const out = res.stdout.trim();
        const text = out.startsWith("{") ? parseDecision(out).context ?? "" : out;
        if (text) parts.push(text);
      }
      if (parts.length) {
        pi.sendMessage(
          { customType: "plugin-hooks", content: parts.join("\n\n"), display: true },
          { deliverAs: "nextTurn" },
        );
      }
    });
  }
}
"""


def render(slots, skipped, notes):
    if skipped or notes:
        lines = ["//", "// Not exported to pi:"]
        for plugin, event, matcher, kind, script, reason in skipped:
            lines.append(
                f"//   - {plugin} {event} [{matcher or '*'}] type={kind} "
                f"script={script}: {reason}"
            )
        for plugin, event, matcher, script, note in notes:
            lines.append(f"//   ~ {plugin} {event} [{matcher}] script={script}: {note}")
        report = "\n".join(lines)
    else:
        report = "//"
    return (
        TS_TEMPLATE.replace("__MARKER__", GENERATED_MARKER)
        .replace("__SKIP_REPORT__", report)
        .replace("__TOOL_CALL__", json.dumps(slots["tool_call"], indent=2))
        .replace("__TOOL_RESULT__", json.dumps(slots["tool_result"], indent=2))
        .replace("__SESSION_START__", json.dumps(slots["session_start"], indent=2))
    )


def parse_args(argv):
    usage = __doc__.strip().splitlines()[-1]
    positional, extra = [], set()
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--allow" and i + 1 < len(argv):
            extra.add(argv[i + 1])
            i += 2
        elif arg.startswith("--allow="):
            extra.add(arg.split("=", 1)[1])
            i += 1
        elif arg.startswith("-"):
            print(
                f"generate-pi-hook-extension.py: unknown argument: {arg}\n{usage}",
                file=sys.stderr,
            )
            sys.exit(2)
        else:
            positional.append(arg)
            i += 1
    if len(positional) != 2:
        print(usage, file=sys.stderr)
        sys.exit(2)
    return Path(positional[0]).resolve(), Path(positional[1]).resolve(), extra


def main(argv):
    repo_root, out_dir, extra = parse_args(argv)
    allowlist = set(PI_SAFETY_ALLOWLIST) | extra

    print("=== PI HOOK EXPORT ===")
    plugin_dirs = [p for p in repo_root.glob("*-plugin") if p.is_dir()]
    plugins, slots, skipped, notes, scripts = collect(repo_root, allowlist)

    ext_dir = out_dir / "extensions" / EXTENSION_NAME
    if ext_dir.exists():
        index = ext_dir / "index.ts"
        if not index.is_file() or GENERATED_MARKER not in index.read_text(
            errors="replace"
        ):
            print(
                f"STATUS=ERROR\nISSUE_COUNT=1\nISSUES:\n  - SEVERITY=ERROR "
                f"TYPE=foreign_output_dir MSG={ext_dir} exists and was not generated here"
            )
            print("=== END PI HOOK EXPORT ===")
            return 1
        shutil.rmtree(ext_dir)
    ext_dir.mkdir(parents=True)
    copied, libs = copy_scripts(repo_root, scripts, ext_dir)
    (ext_dir / "index.ts").write_text(render(slots, skipped, notes))

    for plugin in sorted(plugins):
        stats = plugins[plugin]
        print(
            f"PLUGIN={plugin} SOURCES={','.join(stats['sources'])} "
            f"EXPORTED={stats['exported']} SKIPPED={stats['skipped']}"
        )
        for p, event, matcher, kind, script, reason in skipped:
            if p == plugin:
                shown = matcher or '""'
                print(
                    f"  SKIP event={event} matcher={shown} type={kind} "
                    f"script={script} reason={reason}"
                )
        for p, event, matcher, script, note in notes:
            if p == plugin:
                print(f"  NOTE event={event} matcher={matcher} script={script} {note}")

    exported = sum(s["exported"] for s in plugins.values())
    inline = sum(1 for s in plugins.values() if "plugin.json" in s["sources"])
    issues = []
    if plugin_dirs and not plugins:
        issues.append(
            "SEVERITY=ERROR TYPE=nothing_scanned MSG=plugin dirs present "
            "but no hook manifest was discovered"
        )
    elif plugins and exported == 0:
        issues.append(
            "SEVERITY=WARN TYPE=nothing_exported MSG=manifests found but "
            "no hook is in the pi safety allowlist"
        )

    print(f"HOOK_PLUGINS_SCANNED={len(plugins)}")
    print(f"INLINE_MANIFESTS={inline}")
    print(f"EXPORTED_HOOKS={exported}")
    print(f"TOOL_CALL_ENTRIES={len(slots['tool_call'])}")
    print(f"TOOL_RESULT_ENTRIES={len(slots['tool_result'])}")
    print(f"SESSION_START_ENTRIES={len(slots['session_start'])}")
    print(f"SKIPPED_HOOKS={len(skipped)}")
    print(f"COPIED_SCRIPTS={copied}")
    print(f"COPIED_LIBS={','.join(libs) or '-'}")
    print(f"EXTENSION=extensions/{EXTENSION_NAME}/index.ts")
    status = (
        "ERROR"
        if any("SEVERITY=ERROR" in i for i in issues)
        else ("WARN" if issues else "OK")
    )
    print(f"STATUS={status}")
    print(f"ISSUE_COUNT={len(issues)}")
    if issues:
        print("ISSUES:")
        for issue in issues:
            print(f"  - {issue}")
    print("=== END PI HOOK EXPORT ===")
    return 1 if status == "ERROR" else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
